USE MASTER
GO

CREATE DATABASE SISVENTA
GO

USE SISVENTA

CREATE TABLE CARGO
(ID_CARGO INT IDENTITY PRIMARY KEY,
CARGO VARCHAR(50),
SUELDO DECIMAL)

CREATE TABLE TRABAJADOR
(ID_TRABAJADOR INT IDENTITY PRIMARY KEY,
NOMBRE VARCHAR(50),
APELLIDOS VARCHAR(60),
TIPO_DOCUMENTO VARCHAR(50),
NUMERO_DOCUMENTO VARCHAR(11),
SEXO VARCHAR(50),
FECHA_NAC DATE,
TELEFONO INT,
EMAIL VARCHAR(60),
DIRECCION VARCHAR(100),
ID_CARGO INT,
USUARIO VARCHAR(20),
PASSWORD VARCHAR(20))

/* CREATE TABLE FACTURA
(ID_FACTURA INT IDENTITY PRIMARY KEY,
ID_CLIENTE INT,
SERIE VARCHAR(10),
NUMERO INT,
SUBTOTAL MONEY,
IGV MONEY,
TOTAL MONEY,
FECHA_FAC DATE)

CREATE TABLE DETALLE_FACTURA
(ID_DET_FACTURA INT IDENTITY PRIMARY KEY,
ID_FACTURA INT,
ID_PRODUCTO INT,
CANTIDAD INT,
VALOR_U MONEY,
IMPORTE MONEY)*/

CREATE TABLE PRESENTACION
(ID_PRESENTACION INT IDENTITY PRIMARY KEY,
PRESENTACION VARCHAR(50),
DESCRIPCION VARCHAR(50))
GO
--TABLA DE CATEGORIA PRODUCTO-
CREATE TABLE CATEGORIA
(ID_CATEGORIA INT IDENTITY PRIMARY KEY,
CATEGORIA VARCHAR(50),
DESCRIPCION VARCHAR(50))
GO

CREATE TABLE PRODUCTO
(ID_PRODUCTO INT IDENTITY PRIMARY KEY,
ID_CATEGORIA INT,
ID_PRESENTACION INT,
PRODUCTO VARCHAR(100),
DESCRIPCION VARCHAR(100),
UBICACION VARCHAR(50),
PRECIO_COMPRA DECIMAL(18,2),
PRECIO_VENTA DECIMAL(18,2),
STOCK_INICIAL INT,
STOCK_ACTUAL INT,
FECHA_VENCIMIENTO DATE)

CREATE TABLE PROVEEDOR
(ID_PROVEEDOR INT IDENTITY PRIMARY KEY,
PROVEEDOR VARCHAR(50),
TIPO_DOCUMENTO VARCHAR(50),
NUMERO_DOCUMENTO VARCHAR(11),
TELEFONO INT,
EMAIL VARCHAR(50),
DIRECCION VARCHAR(100),
SITIOWEB VARCHAR(50))

CREATE TABLE INGRESO
(ID_INGRESO INT IDENTITY PRIMARY KEY,
SERIE VARCHAR(10),
NUMERO VARCHAR(10),
FECHA DATE,
ID_PROVEEDOR INT,
TIPO_COMPROBANTE VARCHAR(50),
SUBTOTAL DECIMAL(18,2),
IGV DECIMAL(18,2),
TOTAL DECIMAL(18,2),
ESTADO VARCHAR(50),
TIPO_INGRESO VARCHAR(100),
TRABAJADOR VARCHAR(20))

CREATE TABLE DETALLE_INGRESO
(ID_DETALLE_INGRESO INT IDENTITY PRIMARY KEY,
ID_INGRESO INT,
ID_PRODUCTO INT,
CANTIDAD INT,
PRECIO_COMPRA DECIMAL(18,2),
PRECIO_VENTA DECIMAL(18,2),
IMPORTE DECIMAL(18,2),
FECHA_VENCIMIENTO DATE)

CREATE TABLE CLIENTE
(ID_CLIENTE INT IDENTITY PRIMARY KEY,
CLIENTE VARCHAR(100),
TIPO_DOCUMENTO VARCHAR(50),
NUMERO_DOCUMENTO VARCHAR(11),
SEXO VARCHAR(50) ,
FECHA_NAC DATE,
TELEFONO INT,
EMAIL VARCHAR(60),
DIRECCION VARCHAR(100))

CREATE TABLE VENTAS
(ID_VENTA INT IDENTITY PRIMARY KEY,
ID_CLIENTE INT,
SERIE VARCHAR(10),
NUMERO VARCHAR(10),
FECHA_VENTA DATE,
TIPO_COMPROBANTE VARCHAR(50),
SUBTOTAL DECIMAL(18,2),
TOTAL_DESCUENTO DECIMAL(18,2),
IGV DECIMAL(18,2),
TOTAL DECIMAL(18,2),
ESTADO VARCHAR(50),
TOTAL_LETRAS VARCHAR(200),
TRABAJADOR VARCHAR(20))

CREATE TABLE DETALLE_VENTAS
(ID_DET_VENTA INT IDENTITY PRIMARY KEY,
ID_VENTA INT,
ID_PRODUCTO INT,
CANTIDAD INT,
PRECIO_VENTA DECIMAL(18,2),
DESCUENTO DECIMAL(18,2),
IMPORTE DECIMAL(18,2))

-------------------------------RELACIONES-------------------------------------...

/*ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT FACTURA_DETALLE_F FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA);
ALTER TABLE FACTURA ADD CONSTRAINT FACTURA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);
ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT DETALLE_FAC_PRODCUTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO);*/

ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA);
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_PRESENTACION FOREIGN KEY (ID_PRESENTACION) REFERENCES PRESENTACION(ID_PRESENTACION);

ALTER TABLE TRABAJADOR ADD CONSTRAINT TRABAJADOR_CARGO FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO);
/*ALTER TABLE INGRESO ADD CONSTRAINT INGRESO_TRABAJADOR FOREIGN KEY (ID_TRABAJADOR) REFERENCES TRABAJADOR(ID_TRABAJADOR);
ALTER TABLE VENTAS ADD CONSTRAINT VENTAS_TRABAJADOR FOREIGN KEY (ID_TRABAJADOR) REFERENCES TRABAJADOR(ID_TRABAJADOR);*/

ALTER TABLE DETALLE_INGRESO ADD CONSTRAINT DETALLECOMPRAS_INGRESO FOREIGN KEY (ID_INGRESO) REFERENCES INGRESO(ID_INGRESO);
ALTER TABLE DETALLE_INGRESO ADD CONSTRAINT DETALLEINGRESO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO);
ALTER TABLE INGRESO ADD CONSTRAINT INGRESO_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR);

ALTER TABLE DETALLE_VENTAS ADD CONSTRAINT DETALLEVENTAS_VENTAS FOREIGN KEY (ID_VENTA) REFERENCES VENTAS(ID_VENTA);
ALTER TABLE DETALLE_VENTAS ADD CONSTRAINT DETALLEVENTAS_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO);
ALTER TABLE VENTAS ADD CONSTRAINT VENTAS_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);
GO

CREATE TRIGGER ACTUALIZAR_PRODUCTO
ON DETALLE_INGRESO
FOR INSERT
AS
 update P   set P.STOCK_ACTUAL=P.STOCK_ACTUAL +D.CANTIDAD, P.PRECIO_COMPRA =D.PRECIO_COMPRA,P.PRECIO_VENTA =D.PRECIO_VENTA,P.FECHA_VENCIMIENTO =D.FECHA_VENCIMIENTO  FROM PRODUCTO AS P 
INNER JOIN inserted AS D ON D.ID_PRODUCTO =P.ID_PRODUCTO 
GO


DROP TRIGGER DESMINUIR_STOCK
ON DETALLE_VENTAS 
FOR INSERT
AS
update P   set P.STOCK_ACTUAL=P.STOCK_ACTUAL -D.CANTIDAD FROM PRODUCTO AS P 
INNER JOIN inserted AS D ON D.ID_PRODUCTO =P.ID_PRODUCTO WHERE P.ID_PRODUCTO = D.ID_PRODUCTO
GO
-------------------------------------------------------------------------------------------------------------------------------------------------------------
--REGISTROS CARGOS DE TRABAJADORES --...
INSERT INTO CARGO VALUES('ADMINISTRADOR',50000)
INSERT INTO CARGO VALUES('VENDEDOR',1500)
INSERT INTO CARGO VALUES('LIMPIEZA',1000)

--REGISTROS DE TRABAJADORES CON SU RESPECTIVO CARGO--
INSERT INTO TRABAJADOR VALUES('KELVIN','RIVADENEIRA FABIAN','DNI','75123787','MASCULINO','10-10-10',985171277,'KELVINFABIAN98@GMAIL.COM','AV BOQUERON - PERU',1,'ADMIN','e9MX7Vzun7Y=')

--REGISTROS DE CATEGORIAS DE LOS PRODUCTOS--
INSERT INTO CATEGORIA VALUES('BEBIDAS','BEBIDAS EN GENERAL')
INSERT INTO CATEGORIA VALUES('FRUTAS Y VERDURAS','FRUTAS Y VERDURAS EN GENERAL')
INSERT INTO CATEGORIA VALUES('ENLATADOS','BEBIDAS EN GENERAL')
INSERT INTO CATEGORIA VALUES('GOLOSINAS','BEBIDAS EN GENERAL')

--REGISTROS  DE LOS PRESENTACIONES DE LOS PRODUCTOS--
INSERT INTO PRESENTACION VALUES('UND','UNIDAD')
INSERT INTO PRESENTACION VALUES('kG','KILOGRAMOS')

--REGISTROS DE LOS PRODUCTOS  CON SU RESPECTIVO CATEGORIA Y PRESENTACION--
INSERT INTO PRODUCTO VALUES(1,1,'GASEOSA 900L','GASEOSA 900ML','CONGELADORA',0,0,0,0,'05-03-2019')
INSERT INTO PRODUCTO VALUES(2,2,'LIMON SUTIL AGRIO','LIMON SUTIL','CONGELADORA',0,0,0,0,'05-03-2019')
INSERT INTO PRODUCTO VALUES(1,1,'SPORADE 650ML','SPORADE 650ML','CONGELADORA',0,0,0,0,'05-03-2019')
INSERT INTO PRODUCTO VALUES(3,1,'ATUN DON LUCHO FILETE','ATUN DON LUCHO FILETE','CONGELADORA',0,0,0,0,'05-03-2019')
INSERT INTO PRODUCTO VALUES(4,1,'GALLETAS CARITAS CON CHOCOLATE','GALLETAS CARITAS CON CHOCOLATE','VITRINA',0,0,0,0,'05-03-2019')

--REGISTRO DE LOS CLIENTES--
INSERT INTO CLIENTE VALUES('PEPE RAMIREZ','DNI','87654321','MASCULINO','10-10-1998',963852741,'PEPE@HOTMAIL.COM','AV LIMA - PERU')

--REGISTRO DE LOS PROVEEDORES --
INSERT INTO PROVEEDOR VALUES('PRODUCTOS GLORIA S.A','RUC','147852369',0168547,'GLORIASA@GMAIL.COM','AV REPUBLICA LIMA - PERU','WWW.GLORIA.COM.PE')

--INGRESO DE PRODUCTOS CON SUS RESPECTIVO DETALLE--
INSERT INTO INGRESO VALUES('2019','000002','26-02-2019',1,'FACTURA',50,9,59, 'INGRESADO','COMPRA','ADMIN')
INSERT INTO DETALLE_INGRESO VALUES(5,1,10,2,5,10,'26-02-2019')

--VENTAS DE PRODUCTOS CON SUS RESPECTIVO DETALLE--
INSERT INTO VENTAS VALUES(1,'F001','000009','26-02-2019','FACTURA',7.5,1.35,8.85,'OCHENTA Y CINCO ','ADMIN')
INSERT INTO DETALLE_VENTAS VALUES(2004,1,8,1.5,0,7.5)

--CONSULTAS--...
SELECT*FROM CARGO
SELECT*FROM TRABAJADOR
SELECT*FROM CATEGORIA
SELECT*FROM PRESENTACION
SELECT*FROM PRODUCTO
SELECT*FROM CLIENTE
SELECT*FROM PROVEEDOR
SELECT*FROM INGRESO
SELECT*FROM DETALLE_INGRESO
SELECT*FROM VENTAS
SELECT*FROM DETALLE_VENTAS

SELECT V.ID_VENTA,V.NUMERO AS NUMERO_VENTA,V.SERIE,C.CLIENTE ,V.TIPO_COMPROBANTE,V.SUBTOTAL,V.IGV,V.TOTAL,V.FECHA_VENTA,V.TRABAJADOR  AS VENDEDOR FROM VENTAS V 
INNER JOIN CLIENTE C ON V.ID_CLIENTE=C.ID_CLIENTE 

SELECT  DV.CANTIDAD,P.PRODUCTO,DV.PRECIO_VENTA,DV.DESCUENTO,DV.IMPORTE FROM DETALLE_VENTAS DV 
INNER JOIN VENTAS V ON DV.ID_VENTA=V.ID_VENTA INNER JOIN PRODUCTO P ON P.ID_PRODUCTO =DV.ID_PRODUCTO 

SELECT V.ID_VENTA,V.NUMERO AS NUMERO_VENTA,V.SERIE,C.CLIENTE,V.TIPO_COMPROBANTE,V.SUBTOTAL,V.IGV,V.TOTAL,V.FECHA_VENTA,V.TRABAJADOR  AS VENDEDOR,
 DV.CANTIDAD,P.PRODUCTO,DV.PRECIO_VENTA,DV.DESCUENTO,DV.IMPORTE
FROM DETALLE_VENTAS DV INNER JOIN
 VENTAS V ON DV.ID_VENTA = V.ID_VENTA INNER JOIN
 CLIENTE C ON V.ID_CLIENTE = C.ID_CLIENTE
  INNER JOIN PRODUCTO P ON DV.ID_PRODUCTO = P.ID_PRODUCTO WHERE (V.ID_VENTA = v.ID_VENTA )

--delete  from INGRESO  where  ID_INGRESO  =1003

/*delete from FACTURA where ID_FACTURA=1
update CLIENTE  set NOMBRE ='AA', APELLIDO_P ='AA'
  where ID_CLIENTE=1
select max(ID_FACTURA)+1 from FACTURA
SELECT TOP 1 * FROM FACTURA ORDER BY ID_FACTURA DESC*/
--TRIGEERS PARA ACTUALIZAR STOCK Y PRECIO DE COMPRA Y VENTA--

Select PASSWORD from TRABAJADOR where USUARIO=USUARIO 
select * from TRABAJADOR where USUARIO=USUARIO 

/*CREATE OR REPLACE TRIGGER TR_ARTICULOS
BEFORE INSERT OR DELETE OR UPDATE OF STOCK_ACTUAL, PRECIO_COMPRA ON PRODUCTO
FOR each ROW
BEGIN
dbms_output.put_line('triger diaparado');*/

SELECT*FROM VENTAS WHERE  FECHA_VENTA BETWEEN '15-05-2019' AND '15-05-2019'
SELECT MAX(Numero) FROM INGRESO   ORDER BY NUMERO DESC
